---
- name: "Prepare"
  hosts: all
  gather_facts: false
  vars:
    postfix_mydomain: "example.com"
    postfix_relayhost: "[smtp.example.com]:587"
    postfix_sasl_username: "username"
    postfix_sasl_password: "password"
    postfix_root_alias: "foobar@outlook.com"
    postfix_mail_send_domain: "example.com"
  roles:
    - role: "salvoxia.postfix_send_only_relay"
