---
- name: "Set mydomain in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^#?mydomain"
    line: "mydomain = {{ postfix_mydomain }}"
    state: present
  notify:
    - "Restart postfix"
  when: postfix_mydomain is defined

- name: "Set myhostname in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^#?myhostname"
    line: "myhostname = {{ postfix_myhostname }}"
    state: present
  notify:
    - "Restart postfix"
  when: postfix_myhostname is defined

- name: "Set myorigin in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^#?myorigin"
    line: "myorigin = {{ postfix_myorigin }}"
    state: present
  notify:
    - "Restart postfix"
  when: postfix_myorigin is defined

- name: "Set mydestination in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^#?mydestination"
    line: "mydestination = {{ postfix_mydestination }}"
    state: present
  notify:
    - "Restart postfix"
  when: postfix_mydestination is defined

- name: "Set inet_interfaces in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^#?inet_interfaces"
    line: "inet_interfaces = {{ postfix_inet_interfaces }}"
    state: present
  notify:
    - "Restart postfix"
  when: postfix_inet_interfaces is defined

- name: "Set root alias in aliases"
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^root"
    line: "root: {{ postfix_root_alias }}"
    state: present
  notify: "Run newaliases"
  when: postfix_root_alias is defined
