---
- name: "Ensure postfix is installed (apt)"
  ansible.builtin.apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"

- name: "Ensure SASL packages are installed (apt)"
  ansible.builtin.apt:
    name:
      - sasl2-bin
      - libsasl2-modules
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"
