---
# tasks for postfix_send_only_relay

- name: "Gathering facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Assert"
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: "Become block"
  become: true
  block:
    - name: "Install"
      ansible.builtin.include_tasks: install.yml

    - name: "Flush handlers"
      ansible.builtin.meta: flush_handlers

    - name: "Configure"
      ansible.builtin.include_tasks: configure.yml

    - name: "Auth"
      ansible.builtin.include_tasks: auth.yml

    - name: "Flush handlers"
      ansible.builtin.meta: flush_handlers

    - name: "Send Email"
      ansible.builtin.include_tasks: send_email.yml
      when: postfix_test_send_email

    - name: "Ensure postfix is started and enabled on boot"
      ansible.builtin.service:
        name: postfix
        enabled: true
        state: started
