---
- name: "Gather facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Assert"
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: "Install"
  become: true
  ansible.builtin.include_tasks: install.yml

- name: "Configure"
  become: true
  ansible.builtin.include_tasks: configure.yml

- name: "Auth"
  become: true
  ansible.builtin.include_tasks: auth.yml

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Send Email"
  when: postfix_test_send_email
  become: true
  ansible.builtin.include_tasks: send_email.yml
