---
- name: "Update apt cache (Debian Family)"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: "Ensure postfix is installed"
  ansible.builtin.package:
    name: postfix
    state: present

- name: "Ensure SASL packages are installed (Debian Family)"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - sasl2-bin
    - libsasl2-modules
  when: ansible_os_family == "Debian"

- name: "Install SASL packages (RedHat Family)"
  ansible.builtin.package:
    name:
      - cyrus-sasl
      - cyrus-sasl-plain
      - cyrus-sasl-lib
    state: present
  when: ansible_os_family == "RedHat"

- name: "Ensure postfix is started and enabled at boot"
  ansible.builtin.service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"

# Configure Postfix Relayhost
- name: "Configure Postfix Relayhost"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^relayhost"
    line: "relayhost = {{ postfix_relayhost }}"
    state: present
  notify: "Restart postfix"

- name: "Add SASL config to main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regex: "smtp_sasl_auth_enable"
      line: "smtp_sasl_auth_enable = yes"
    - regex: "smtp_sasl_password_maps"
      line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
    - regex: "smtp_sasl_security_options"
      line: "smtp_sasl_security_options = noanonymous"
    - regex: "smtp_tls_security_level"
      line: "smtp_tls_security_level = may"
    - regex: "header_size_limit"
      line: "header_size_limit = 4096000"
  notify: "Restart postfix"

- name: "Ensure sasl_passwd file exists"
  ansible.builtin.file:
    path: /etc/postfix/sasl_passwd
    state: touch
    owner: root
    group: postfix
    mode: 0440

- name: "Configure SASL Password"
  ansible.builtin.lineinfile:
    path: /etc/postfix/sasl_passwd
    regexp: "^{{ postfix_relayhost }}"
    line: "{{ postfix_relayhost }} {{ postfix_sasl_username }}:{{ postfix_sasl_password | quote }}"
    state: present
  notify: "Restart postfix"

#TODO: add idempotancy check
- name: "Postmap sasl_passwd"
  ansible.builtin.command: "postmap /etc/postfix/sasl_passwd"
  notify:
    - "Restart postfix"
    - "Restart saslauthd"
  changed_when: false

- name: "Check sasl_passwd.db exists"
  ansible.builtin.stat:
    path: /etc/postfix/sasl_passwd.db
  register: sasl_passwd_db

- name: "Ensure sasl_passwd.db permissions are correct"
  ansible.builtin.file:
    path: "/etc/postfix/sasl_passwd.db"
    state: touch
    owner: root
    group: postfix
    mode: 0600
  when: sasl_passwd_db.stat.exists
