---
- name: "Run Postmap sasl_passwd"
  become: true
  ansible.builtin.command: postmap /etc/postfix/sasl_passwd
  changed_when: true

- name: "Restart saslauthd"
  become: true
  ansible.builtin.service:
    name: saslauthd
    state: restarted

- name: "Run newaliases"
  become: true
  ansible.builtin.command: newaliases
  changed_when: true

- name: "Restart postfix"
  become: true
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: "Restart Postfix Suse"
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: ansible_os_family == "Suse"
