---
- name: "Postmap sasl_passwd"
  ansible.builtin.command: postmap /etc/postfix/sasl_passwd

- name: "Restart postfix"
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: "Restart saslauthd"
  ansible.builtin.service:
    name: saslauthd
    state: restarted
